### ISSUE TITLE
Repository management: Version 2.0.1 git-tag is missing

### ISSUE THREAD

**Issue by jenisys** [perrygoy/screenpy#11]
The newest tag is "2.0.0" in the Git repository.
pypi.org contains a version "2.0.1" which is also named in "setup.py" file.

HINT:
Current HEAD of repository seems to have changed compared to pypi version of `screenpy-2.0.1`.
Maybe you have not pushed the tag from your local workspace to the Github repository server (or forgot to tag the release).

**Comment by perrygoy** [comment]
Nice catch! I totally forgot to do that. I've added the tag to the commit hash.

You're right that the current HEAD is different than 2.0.1, i'm gearing up for a 2.1.0 release and got a little too excited with my pushing, so... here we are. :)
