### ISSUE TITLE
docs: Add selenium-webdriver installation hint => geckodriver is missing (for tests)

### ISSUE THREAD

**Issue by jenisys** [perrygoy/screenpy#13]
When I run the tests with pytest, several tests fail with the following problem:

```bash
$ pytest
...
selenium.common.exceptions.WebDriverException: Message: 'geckodriver' executable needs to be in PATH.
...
```

DESIRED CHANGE:
* Add this information/hint to the INSTALLATION page in the docs 
  (like: `On macOS: brew install geckodriver (for Firefox)`, etc.)
  => Selenium webdriver external dependency: Firefox and geckodriver need to be installed (for running tests)

SEE ALSO:
* https://screenpy-docs.readthedocs.io/en/latest/installation.html
* https://github.com/mozilla/geckodriver/releases

RELATED TO PROBLEM: Selenium missing geckodriver
* https://stackoverflow.com/questions/40208051/selenium-using-python-geckodriver-executable-needs-to-be-in-path
* https://stackoverflow.com/questions/40186299/selenium-opens-browser-but-doesnt-load-page

**Comment by perrygoy** [comment]
This is a very well-written ticket. Thank you for submitting it!

I'll make sure to add this information to the Installation page. I'm in the middle of a huge docs rework, so i'll close this ticket once those changes make it up.

**Comment by perrygoy** [comment]
I added a quick mention at the bottom of the [Installation](https://github.com/perrygoy/screenpy/blob/trunk/docs/installation.rst) page. 

@jenisys how's that look to you?

**Comment by jenisys** [comment]
Yes, as expected.
