### ISSUE TITLE
QuickStart simple fail , 'Text' object has no attribute 'viewed_by'

### ISSUE THREAD

**Issue by kyoliu** [perrygoy/screenpy#2]
i pip install 
run  QuickStart simple
there is no viewed_by in Text class
![螢幕快照 2019-07-24 下午5 14 35](https://user-images.githubusercontent.com/28671990/61781560-26dd9180-ae37-11e9-881d-2201d6db88b3.png)

**Comment by perrygoy** [comment]
Thanks @kyoliu! I forgot to update the Quickstart documentation after standardizing around the new method, `answered_by`.

I've pushed out a fix in 0.3.0, please do a `pip3 install -U screenpy` and let me know if everything's working!

**Comment by perrygoy** [comment]
Since the quickstart has changed so much at this point, this issue is no longer relevant. I hope it's all right with you that i'm closing this!
