### ISSUE TITLE
BaseAction, BaseAbility, BaseQuestion etc are still present after install from pip?

### ISSUE THREAD

**Issue by bandophahita** [perrygoy/screenpy#25]
I noticed the comment from release 2.1.0 says the classes `BaseAction`, `BaseAbility`, etc had been removed.  While they don't appear in the repo, for some reason they are still showing up in the package installed by `pip`.

**Comment by perrygoy** [comment]
That is strange, but i can't reproduce this with 3.0.2:

```
(env) [16:01:59] perry github $ pip list
Package               Version
--------------------- ---------
...
screenpy              3.0.2
...
(env) [16:02:02] perry github $ python3
Python 3.9.2 (default, Feb 24 2021, 13:30:36) 
[Clang 12.0.0 (clang-1200.0.32.29)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import screenpy
>>> from screenpy.actions import BaseAction
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ImportError: cannot import name 'BaseAction' from 'screenpy.actions' (/Users/perry/Documents/git/screenpy/examples/github/env/lib/python3.9/site-packages/screenpy/actions/__init__.py
```

What version of ScreenPy did you install?

**Comment by bandophahita** [comment]
I started with 2.9?  updated to 3.0.1.  I haven't updated to 3.0.2 since I'm on python 3.7 still.
 
When I started building my Actions and Tasks I saw there is a module `base_action.py` in the actions sub package (folder).  I started using those as my base class.  It wasn't until I actually did a fork and created a project in pycharm until I saw those base classes were no longer available in the source.

![image](https://user-images.githubusercontent.com/4211287/110343645-516f6480-7ff2-11eb-812c-c4b7253246f6.png)

**Comment by perrygoy** [comment]
Weird. Yeah i'm not sure what they're still doin' there or how to get rid of 'em.

**Comment by bandophahita** [comment]
I've never done package creation but I'm wondering if there is something in the process that allows caching vs clean creation?  That was my first thought when I noticed it. As if somehow pypi packager needs to be told 'create release package without using cache'.  

My other thought is something in the way setuptools works? 

OR... (I just realized) I ran the update to the package via Pycharm.  That's not something I typically do. Might be something there I should look at.
I'll try uninstalling the package normally and see if installing the older version still has it vs the newer version.

**Comment by bandophahita** [comment]
I think I can safely rule out pycharm.
`pip uninstall screenpy` followed by `pip install screenpy=3.0.1` still had the `base_` modules in the library.

**Comment by perrygoy** [comment]
I was also able to reproduce the same, installing **3.0.1**. I wonder if i messed up the bundle somehow when i uploaded it to PyPI.

Maybe i should add a note to `HISTORY.md` about how **3.0.1** still has those deprecated base classes, somehow?

**Comment by bandophahita** [comment]
I don't see any harm in adding something to the history.   Could even be a little cheeky; "Removed old modules, for _real_ this time"

**Comment by perrygoy** [comment]
Added the cheeky line to `HISTORY.md`! 🎩 💁
