### ISSUE TITLE
This is to say

### ISSUE THREAD

**Issue by andest01** [perrygoy/screenpy#3]
I have stolen
the screenplay template
that was in
the `README.md`

and which
you were probably
saving
for MIT License

Forgive me
it was funny
so engaging
and so edge

**Comment by andest01** [comment]
![image](https://user-images.githubusercontent.com/1424223/63232288-10371a00-c1ec-11e9-9b15-322b8d637b6c.png)

**Comment by andest01** [comment]
![image](https://user-images.githubusercontent.com/1424223/63232305-45dc0300-c1ec-11e9-8627-8cf19fc5118a.png)

**Comment by perrygoy** [comment]
Go, with my blessing. 
Go forth and multiply.
