### ISSUE TITLE
ImportError on Python <3.9 because of Protocol.

### ISSUE THREAD

**Issue by perrygoy** [perrygoy/screenpy#30]
I missed a spot on the Protocol revert in screenpy/actions/__init__.py. 

Hey @perrygoy you should have `tox` check multiple environments instead of just 3.9, hey?

**Comment by bandophahita** [comment]
I support this.  (perhaps out of selfish reasons since project I am working on happens to be in 3.7 atm)

However, if it doesn't make sense to support older versions of python then I recommend setting `python_requires=">=3.9"` in the setup.cfg.

**Comment by perrygoy** [comment]
Fixed in 3.0.4!
