### ISSUE TITLE
Add action to answer a question about a target next time you see it.

### ISSUE THREAD

**Issue by perrygoy** [perrygoy/screenpy#33]
This is one of the tickets taken out of the private ScreenPy Trello board, for better exposure of what work is on the horizon.

Currently, when we need to take note of some information about a target during a test (say we need to compare it to the value later), we have to do this somewhat awkward dance:

```python
when(the_actor).attempts_to(
    Click.on_the(MY_ACCOUNT_BUTTON),
    Wait.for_the(USER_FIRST_NAME_FIELD),
)

first_name_before = Text.of_the(USER_FIRST_NAME_FIELD).answered_by(the_actor)

and_(the_actor).attempts_to(
    ChangeFirstNameTo("Quincy" + timestamp)
)

then(the_actor).should_see_the(
    (Text.of_the(USER_FIRST_NAME_FIELD), IsNot(EqualTo(first_name_before))
)
```

It would be really neat if we could do something like...

```python
when(the_actor).attempts_to(
    Click.on_the(MY_ACCOUNT_BUTTON),
    Wait.for_the(USER_FIRST_NAME_TEXT),
    Remember.the(Text.of_the, USER_FIRST_NAME_FIELD),
    ChangeFirstNameTo("Quincy" + timestamp)
)

then(the_actor).should_see_the(
    (
        Text.of_the(USER_FIRST_NAME_FIELD), 
        IsNot(EqualTo(Remembered(Text.of_the, USER_FIRST_NAME_FIELD)))
    )
)
```

I've tried to implement this a couple times now, but always get bogged down with where to store the remembered data. On the actor? In the ability? I haven't figured out a way yet that didn't feel like i was adding some spaghetti to the code. It feels like there should be an elegant way to do this.

The `Remember` action (or whatever it makes sense to call it; `MakeNoteOf`? `MarkDown`?) will need set up some kind of flag for the target to be noticed, the next time it is `found_by` the actor. Then whatever mechanism is keeping track of what question to ask about that `Target` will need to ask that question of the target—if it is found—and store the answer, somewhere.

Later, the `Remembered` question will take in the question/target pair and produce the answer that was discovered, if there was one.

**Comment by perrygoy** [comment]
Hmm... what if the _target_ is the one that remembers?

**Comment by bandophahita** [comment]
I can't help but ask the question who or what is responsible for remembering variables used in a test? My gut says either the test or the actor is responsible.  

Putting it on the actor likely would result in a new ability.  `Remember` ?

**Comment by bandophahita** [comment]
> Hmm... what if the _target_ is the one that remembers?

That's for sure a violation of SRP.

What if it looked something like this:

```python
when(the_actor).attempts_to(
    Click.on_the(MY_ACCOUNT_BUTTON),
    Wait.for_the(USER_FIRST_NAME_TEXT),
    Remember.the(Text.of_the, USER_FIRST_NAME_FIELD).as_('text_to_recall'),
    ChangeFirstNameTo("Quincy" + timestamp)
)

then(the_actor).should_see_the(
    (
        Text.of_the(USER_FIRST_NAME_FIELD), 
        IsNot(EqualTo(Remembered('text_to_recall')))
    )
)
```
The actor would have an ability that stores anything it needs to recall for later (basically a dictionary) and we just ask for it by key.

**Comment by perrygoy** [comment]
Hey, i like that approach. I hadn't thought of encapsulating it in an ability, weirdly enough. Doing it that way makes it much more straightforward. We've been mulling this over at work for a few weeks now and i think we also sort of converged on the `Remember(Question, Target).as_("key")` approach, too. 

I think the functionality outlined in the original issue is not really feasible, the sort-of sentinel thing. The cool advantage of it is that you could find answers to questions about targets without having to add any `Remember` lines to tasks. That felt pretty neat 'cause then tests would dictate what data they cared about, but it's much more explicit this way, and much less _weird_.

**Comment by perrygoy** [comment]
@bandophahita i've started implementing this ability/action/resolution only to realize that the resolution isn't a resolution, and i'm not sure where to put it. Rather than stew on it for a few days, i thought i'd reach out for some input.

To set the scene, i've settled on the name `TakeNotes` for the ability, `MakeNote/TakeNote` for the action, and `Noted` for the pseudo-resolution. The ability and the action are both fine, but when looking at the resolution, this is how i'm imagining it will work:

```python
the_actor.should_see_the(
    (
        Text.of_the(NAME_FIELD),
        IsNot(EqualTo(TheNoted(Text.of_the, NAME_FIELD).by(the_actor))),
    )
)
```

As i was implementing it as a resolution, i realized there's no matcher. We just want to return the lookup from the actor's stored note in `TakeNotes` from the call to `by`. So... what is this?

I was thinking about putting it in `resolutions` anyway since that seems like the place most people would go looking for it. But that's not... true—it can't just be used like a normal resolution:

```python
# doesn't make sense?
the_actor.should_see_the((Text.of_the(NAME_FIELD), Noted(Text.of_the, NAME_FIELD)))
```

I was wondering if i should have a new category of resolution-helper classes that this would fall under, like `investigations` or `clues` or `tools` something. Or maybe i could just have `Noted` use an implicit `equal_to` matcher and change the name to `EqualToNoted`?

**Comment by perrygoy** [comment]
I think the real snag here is that we need to pass `the_actor` along to this "resolution". That makes it pretty unique. I'm remembering that this is the problem i kept hitting before, and why i was entertaining crazy thoughts like having the `Target` remember the answer to the question.

**Comment by bandophahita** [comment]
My initial thought is the `Noted` object doesn't need to be a resolution; it just needs to be passed to a resolution.  Would that be enough?  Similar to how `HasLength` which is a resolution accepts a length input which is not a resolution; the `Noted` would be the input to a resolution but isn't one itself?

**Comment by bandophahita** [comment]
I'm going to back up and ask the question from a ~~devils advocate~~ fresh perspective; do we need this?

It _seems_  like a lot of effort just to avoid the 'awkward dance'.  It could even be argued that the act of `TakeNote` is less understandable than assigning a variable directly. (*though I'm not sure how much I buy that argument*)

Another way to ask the question is where does the responsibility lie in assigning variables?  Is the actor responsible for that or is the test?  

If the actor is responsible for saving variables, should this be an innate ability all actors have?  
```python
the_actor.notes(Text.of_the, NAME_FIELD)
```

**Comment by perrygoy** [comment]
> The way I'm thinking about it: Abilities make actions possible. So are these both actions? e.g Read/write, save/recall, etc. TakeNote/RemeberNote.

Hm... so maybe the real flow would be something like:

```python
the_actor.attempts_to(
    # ...
    MakeNote.of_the(Text.of_the, NAME_FIELD),
    # ...
)

# one of these, or something like one of these
previous_name = Recall(Text.of_the, NAME_FIELD).as(the_actor)  # ?
previous_name = the_actor.recalls_the(Text.of_the, NAME_FIELD)  # ?

notebook = the_actor.ability_to(TakeNotes)
previous_name = notebook.look_up_the(Text.of_the, NAME_FIELD) # ?

the_actor.should_see_the((Text.of_the(NAME_FIELD), IsNot(EqualTo(previous_name)))
```

I think examining all these options brings me to your next very good question:

> do we need this?

I don't think we _strictly_ do. But i do think it improves the readability of the tests. And i've come back to it like three times, but maybe i should just let this one die.

> where does the responsibility lie in assigning variables?

I think the test is the one that should be dictating what pieces of information are important to test later. If i'm thinking about it in the context of a screenplay, though, the actor wouldn't be the one making these observations. It would be the audience. (Pause for laughs)

More seriously though i think it does make sense for the actor to remember things. Your suggestion to make the `TakeNotes` ability finally got most of the pieces connected for me, it's just this last bit that i can't figure out how to jam in there.

I think i'll try the `EqualToTheNoted(Text.of_the, NAME_FIELD).by(the_actor)` thing and see if i hate it. I'll probably find that out while i'm writing the tests for it.

**Comment by perrygoy** [comment]
@bandophahita so i think i've settled on the approach of using mixins to add extra functionality to some of the resolutions to allow them to use notes. I'm feeling hesitant for a few reasons, probably the silliest of which is that i need to do some funny things to make the words work (e.g. `IsEqualTo` is fine having a `the_noted` method added to it, but `ContainsTheText` needs a different one...).

Adding the mixins has made me think that maybe taking notes is something actors should just be able to do, like an innate ability. It does fit in with the whole "screenplay" flavor of it, actors taking notes. I think it also would make things a bit cleaner, i didn't like the idea of having to make folks add the `TakeNotes` ability to their actors—it didn't feel like something special enough to warrant an ability. Here's the whole thing:

```python3
class TakeNotes:
    """The ability to take notes.

    Examples::

        Perry = AnActor.named("Perry").who_can(TakeNotes())
    """

    def note(self, *notes) -> None:
        """Mark down one or more notes.

        Args:
            notes: a dictionary, a tuple of key/value pairs, or arguments as
                alternating keys and values.
        """
        if len(notes) == 1:
            self.notes.update(notes)
        elif len(notes) % 2 == 0:
            self.notes.update(zip(notes[0::2], notes[1::2]))
        elif notes:
            raise ValueError("TakeNotes.note got an uneven list of keys and values.")

    to_note = note

    def look_up(self, key) -> None:
        """Retrieve a value that was previously noted."""
        return self.notes[key]

    to_look_up = look_up

    def forget(self) -> None:
        """Clear out the stored notes."""
        self.notes = dict()

    def __repr__(self) -> str:
        return "Take Notes"

    __str__ = __repr__

    def __init__(self) -> None:
        self.notes = dict()
```

I don't know. I'm looking for another opinion before i feel sure of this approach. How do you feel about actors being innately able to take notes?

**Comment by perrygoy** [comment]
After taking a moment to start adding the code to make `TakeNotes` an innate ability, i am already leaning away from it. `Actor` is pretty big already and adding this feels out of place.

**Comment by perrygoy** [comment]
I have something pushed up in #42, @bandophahita. If you could take a look at it and let me know what you think, i'd be very grateful. The way i've implemented it there, i do not like it. But i'd like some help figuring out how to make it into something i *do* like.

As i was writing that PR, whenever i looked at the `TakeNotes` ability and the `MakeNote` action, i liked it! But any of the resolution stuff... well, it seemed cool before i started writing it.

**Comment by bandophahita** [comment]
What don't you like?
I'm also having a hard time articulating it, but I'm not sure I like it either.  I was fine until I got to the tests and saw how it was being used.  

This feels rather clunky.  It's pretty much what we talked about and yet I don't want to utilize this ability.   
`Tester.attempts_to(MakeNote.of_the(MockQuestion).as_("test"))` 

The only time I feel it would be worth using would be when I need to access the saved item at a different scope.  
So why don't we like this?**

_** (I'm taking this as a sign to rethink things.)_

**Comment by bandophahita** [comment]
> `Actor` is pretty big already and adding this feels out of place.

Does it have to be part of `Actor` or can this be some sort of default ability?  (_possibly one that cannot be removed?_). 
I like the idea of accessing it like all the other abilities; the only difference is this ability would already be in the actor when it's created.

**Comment by perrygoy** [comment]
I had thought about the default ability idea, but i can't figure out how exactly would be the "right" way. My instinct was to put it in the `__init__` method, but i had a hesitation because i wondered if the actor knowing its default abilities was starting to give too much responsibility to the actor. 

I guess if i think about the actor as an "ability manager" with a couple clerical duties as well, it fits. 

> What don't _you_ like?

I had gotten excited about the mixin part, 'cause that's pretty neat. But seeing it in action, i really disliked it. It feels gross and fragile, where i thought it would be an easy add-in that would offer support for anyone to write custom resolutions that could easily and optionally use noted data. The part i really hate is that i can't figure out an elegant way to handle when people forget to call the `.by` method to supply the actor. 

I've also started thinking about how to split things out in that vision of ScreenPy's future that you planted in me, where there is `screenpy-core` plus the various "expansion packs" for the different, specific abilities. I think this mixin would be nice for that future, but i also think that it sets a weird precedent of one ability corrupting a bunch of other classes.

I dunno; like you, i'm having trouble really putting a finger on what is *wrong* with this approach. It just doesn't feel right.

**Comment by bandophahita** [comment]
I agree the `.by` call feels clumsy.  

*looks off into the sunset.  queue the dream music*

What I really want is to be able to write something like the following and have `Recall` access the actor's ability and pass it on to `IsEqualTo` 
```python
Tester.should_see_the((MockedTextQuestion, IsEqualTo(Recall(key)))
```

but I'd settle for...
```python
Tester.should_see_the((MockedTextQuestion, IsEqualTo(Tester.recall(key)))
```

**Comment by perrygoy** [comment]
> need to call the .by method, it is too easy to be forgotten. .

Yeah, totally agree. I hate that part about it. I decided to just rip out the resolutions bit.

> Maybe we can rewrite the `should_see_the` method to supply the actor.

I had thought about this approach, but i think that would be too disruptive, and it's a little... weird. I guess technically both Questions and Actions have the actor pass themselves in, so maybe it's not too bizarre... i'll think more about this one.

The only snag on that one is that sometimes you might have multiple actors in a test and want to pass values between them using this ability... maybe i'm getting too bogged down on the imagined concrete.

> What I really want is to be able to write something like the following and have `Recall` access the actor's ability and pass it on to `IsEqualTo`

This is exactly how i had hoped this would work. It's weird, having written the very thing that is preventing me from being able to make it work like that, and understanding that i can't make it do that thing, despite all that.

**Comment by perrygoy** [comment]
Anyway @bandophahita, @WandyYing, if you want to take another look at that PR before i merge it, feel free! I think i'm OK with it as it is now, just adding the ability and the action. Maybe someone else will figure out a fancy way to handle the resolution bit in the future.

**Comment by WandyYing** [comment]
> The only snag on that one is that sometimes you might have multiple actors in a test and want to pass values between them using this ability... maybe i'm getting too bogged down on the imagined concrete.

For this one, I think we can use like following: (using your code :) )
```python
the_actor.attempts_to(
    Visit(URL),
    MakeNote.of(TheText.of_the(WELCOME_MESSAGE)).as_("first message"),
    LogIn(),
    Wait.for_the(WELCOME_MESSAGE).to_appear(),
)

# It's just a usage like this, not the final way.
first_message = the_actor.uses_ability_to(TakeNotes).to_look_up("first message")

other_actor.attempts_to(
     Visit(first_message),
)
```

**Comment by WandyYing** [comment]
And, I submitted some comments on your PR. In order to facilitate the follow-up discussion, I also copy a copy to the following.

> Hi @perrygoy Good Job. It's close to perfection. I think it would be better if it could be changed to the following one.
```python
the_actor.attempts_to(
    Visit(URL),
    MakeNote.of(TheText.of_the(WELCOME_MESSAGE)).as_("first message"),
    LogIn(),
    Wait.for_the(WELCOME_MESSAGE).to_appear(),
)

# first_message = the_actor.uses_ability_to(TakeNotes).to_look_up("first message") # delete it

the_actor.should_see_the(
    (Text.of_the(WELCOME_MESSAGE), DoesNot(ReadExactly(Note.of(first_message)))),
)
```
> How do you like add action `Note.of` to retrieves the previously recorded `first_message`?


In addition, I'm also thinking about the possibility of merging `attempts_to` and `should_see_the`.

**Comment by perrygoy** [comment]
> In addition, I'm also thinking about the possibility of merging attempts_to and should_see_the.

Ah, i see, that actually sheds some light on your PR comment. I'm interested in your thoughts there, because my initial reaction was that it couldn't/shouldn't be done, since `attempts_to` and `should_see_the` both have such different expectations about their arguments. 

How do you see that working? What benefits do we gain?

**Comment by WandyYing** [comment]
If we need to verify the results of every action. For example, we do the following tests, the existing solution will be more cumbersome. 
1. Access an address_A and verify the result.
2. Access an address_B and verify the result.
3. balabala
Current:
```python
the_actor.attempts_to(
    Visit(address_A),
)
the_actor.should_see_the(
    verifyA,
)
the_actor.attempts_to(
    Visit(address_B),
)
the_actor.should_see_the(
    verifyB,
)
```
after the merger:
```python
the_actor.attempts_to(
    Visit(address_A),
    verifyA,
    Visit(address_B),
    verifyB,
)
```
So we can sort out the behavior and the expected results linearly. And I think it may solve the problem of `Note.of` getting actors(perhaps?).

But it's going to make a big difference. If necessary, we can open another discussion to "merge".

**Comment by perrygoy** [comment]
@WandyYing i was going to open up a new [discussion](https://github.com/perrygoy/screenpy/discussions) topic for that, do you want me not to? I do have some thoughts about it, but i do agree that they should stay separate. My thoughts were more about test design than anything.

Anyway, i think the PR for this issue (#42) is now in its final form! I'm really happy with how it turned out.

**Comment by WandyYing** [comment]
@perrygoy Yep. Please open a new topic. :)

>Anyway, i think the PR for this issue (#42) is now in its final form! I'm really happy with how it turned out.

Align with you

**Comment by perrygoy** [comment]
OK, i opened #45 to discuss your thoughts! I linked to your comment above, but i see now it's edited with an "ignore this" message.

**Comment by perrygoy** [comment]
PR #42 is merged!
