### ISSUE TITLE
Using values from the last response should be easier.

### ISSUE THREAD

**Issue by perrygoy** [perrygoy/screenpy#35]
This is one of the tickets taken out of the private ScreenPy Trello board, for better exposure of what work is on the horizon.

In ScreenPy v2.1.0, the `MakeAPIRequests` ability was added, along with a slew of API request abilities. Currently, though, in order to do a pretty common flow in API testing of adding headers/values using content from the last response, we have to do this disjointed samba:

```python
when(the_actor).attempts_to(
    SendPOSTRequest.to(TOKEN_URL)
)

bearer_token = BodyOfTheLastResponse().answered_by(the_actor).get("bearer_token")

and_(the_actor).attempts_to(
    AddHeader(Authorization=bearer_token)
    # ...
)
```

It would be much nicer if the `AddHeader` and `SetHeader` actions at least had a built-in way to set a header based on the last response, something like:

```python
when(the_actor).attempts_to(
    SendPOSTRequest.to(TOKEN_URL),
    AddHeader("Authorization").using_value("bearer_token").from_last_response(),
)
```

There's probably a more fluid way to say that, or a better approach. Maybe a different action would make this easier? 🤷

**Comment by WandyYing** [comment]
How about add a layer like Tasks or Actions? It will include the implementation of the operation. For instance,

actions
```
Class GetToken:
       ...
```
features
```
when(the_actor).attempts_to(
    GetToken.with_("Admin"),
    ...
)
```

**Comment by perrygoy** [comment]
Someone had commented on this ticket (but has since deleted it) that you can use tasks to alleviate this problem, and they were right. Making a nice task like `AddAuthenticationToken()` or something would make it much easier to look at.

They also suggested making an action, and i think that might be the right approach. Modifying `AddHeader` or `SetHeaders` would make them too complicated, probably violate the Single Responsibility Principle. Adding a new action or two like `AddHeaderUsingLastResponse` or `AddHeaderFromCookie` would be better!

Now the problem is how to make a fluid English phrase with that base that somehow also provides the header name and value.

**Comment by WandyYing** [comment]
> Someone had commented on this ticket (but has since deleted it) that you can use tasks to alleviate this problem, and they were right. Making a nice task like `AddAuthenticationToken()` or something would make it much easier to look at. That is the approach that i've taken in my own suite, too!
> 
> They also suggested making an action, and i think that might be the right approach. Modifying `AddHeader` or `SetHeaders` would make them too complicated, probably violate the Single Responsibility Principle. Adding a new action or two like `AddHeaderUsingLastResponse` or `AddHeaderFromCookie` would be better.
> 
> Now the problem is how to make a fluid English phrase with that base that somehow also provides the header name and value.

@perrygoy This a good way.

And, in addition to the above, I suggest add an attribute/function to the ability "MakeAPIRequests".  like `request_config` and `modify_config` .

* **request_config**: attribute, List[Dict]. Save the session config, like header and cookie. 
* **modify_config**: function. Modify the session config.
* **extract**:  attribute, dict. Save the value witch need extract from response. And these extracted data will be applied to future requests. Not only next request. 

So,  actions like `AddHeaderUsingLastResponse` or `AddHeaderFromCookie` can using `modify_config` to change the `request_config`. I think it will be better.

**Comment by perrygoy** [comment]
`AddHeaderUsingLastResponse` and the similar actions would be doing something like what you said, yeah! But i don't think the **request_config** etc. methods are necessary—the `requests.Session` object that `MakeAPIRequests` is holding already handles all those things for us. It keeps the headers and cookies information for our API session stored and passes those along to every request.

So you're on the right track, i do think that these new actions will be modifying the session, it's just that we already have the mechanisms they'll be using in place! :)

**Comment by WandyYing** [comment]
Aha, I forgot the `self.response`. `MakeAPIRequests` has all the data we need.  :)

**Comment by perrygoy** [comment]
I think the new `Director` class (added in #42 from issue #33) actually addresses this one, as well! It does mean we have an extra step, but now we can do this:

```python
when(the_actor).attempts_to(
    SendPOSTRequest.to(TOKEN_URL),
    MakeNote.of_the(BodyOfTheLastResponse()).as_("token response")
    AddHeader(Authorization=the_noted("token response")["token"])
```

One could even write a custom question that would extract the "token" from the response, if they wished, and make it even sleeker.

**Comment by perrygoy** [comment]
> now we can do this:
> ```python
> when(the_actor).attempts_to(
>    SendPOSTRequest.to(TOKEN_URL),
>    MakeNote.of_the(BodyOfTheLastResponse()).as_("token response"),
>    AddHeader(Authorization=the_noted("token response")["token"]),
>)
>```

Haha no we can't. See issue #51.

We _can_, however, do this:

```python
when(the_actor).attempts_to(
    SendPOSTRequest.to(TOKEN_URL),
    MakeNote.of_the(BodyOfTheLastResponse()).as_("token response"),
and_(the_actor).attempts_to(
    AddHeader(Authorization=the_noted("token response")["token"]),
)
```

**Comment by perrygoy** [comment]
It seems like, for now at least, we're sticking with the `Director`. The `Director` does make it easier to deal with responses, so... i think i'll close this one!
