### ISSUE TITLE
`Text.of_all` throws TargetingError when no elements are found.

### ISSUE THREAD

**Issue by pgoy-dod** [perrygoy/screenpy#37]
The `Text.of_all` question throws a TargetingError when no elements exist on the page. It seems like it would be better if it just returned an empty list if the targeted element doesn't exist.

(Open to discussion on the desired behavior here.)

**Comment by perrygoy** [comment]
Uh. So i apparently logged this without doing enough digging.

This is already the behavior of `Text.of_all` because this is already the behavior of `Target.all_found_by`, because this is already the behavior of Selenium's `find_elements`. Woops!
