### ISSUE TITLE
Command screenpy-quickstart not found

### ISSUE THREAD

**Issue by IgorGanapolsky** [perrygoy/screenpy#39]
I installed screenpy with `pip install screenpy`.

However, 
> zsh: command not found: screenpy-quickstart

**Comment by perrygoy** [comment]
Hi @IgorGanapolsky! 

You may need to alter your system's `PATH` to include Python binaries. Or you could install `screenpy` in a [virtual environment](https://docs.python.org/3/tutorial/venv.html) like so:

```
python -m env venv
source venv/bin/activate
pip install screenpy
screenpy-quickstart
```

Personally i recommend the virtual environment approach.

Let me know if this fixes the issue! I haven't tried the quickstart script in `zsh` yet.

**Comment by perrygoy** [comment]
Your image didn't attach through the e-mail interface, but since you're replying by e-mail i have a feeling i know what it was.

When i first submitted my response, i mixed up `venv` and `env`. The actual command should be:

```
python -m venv env
```

**Comment by IgorGanapolsky** [comment]
It worked with this command:

python3 -m venv venvsource ./venv/bin/activate

**Comment by perrygoy** [comment]
Great! And you now have access to `screenpy-quickstart.py`?

**Comment by IgorGanapolsky** [comment]
Yes

**Comment by haibgit** [comment]
if you using Ubuntu (linux), using `screenpy-quickstart.py`
![image](https://user-images.githubusercontent.com/10678585/116974464-6281dc80-ace8-11eb-95cf-b49d74571daf.png)
