### ISSUE TITLE
Add `Value` question.

### ISSUE THREAD

**Issue by perrygoy** [perrygoy/screenpy#40]
At least on the websites i've been writing test scripts for, sometimes an `input` element is used to display data. Data that we need to verify.

We don't currently have a question that can get the `value` attribute of elements. It would be nice to have a `Value` question that behaved similar to `Text`, e.g.:

```python
>>> Value.of_the(DATE_INPUT).answered_by(the_actor)
"02/22/2022"
>>> Value.of_all(NAME_INPUTS).answered_by(the_actor)
["Perry", "Jenny", "Ben", "Gina"]
```

**Comment by bandophahita** [comment]
*brainstorm thought*
This type of thing got me wondering if there was a way to combine all the various attributes of an element? (value, text, property, attribute, etc). They are all technically attributes of selenium's `WebElement` and yet we have different questions for them.  

```python
# this reads awkwardly but can be done currently
the_actor.should_see_the((Element(WELCOME_BANNER).text, ReadsExactly("Welcome!")))

# Maybe something like this?  
the_actor.should_see_the((Element.text_of(WELCOME_BANNER), ReadsExactly("Welcome!")))
```

**Comment by perrygoy** [comment]
This is an interesting brainstorm thought. It kinda ties into something that has been bothering me.

So i've got all these questions like `Text`, `Number`, etc. that will act on elements. But then i added `Element`, and now it's confusing, i think. For example, `List` gives back a list of elements but doesn't really make that clear unless you read the documentation.

I think this would also be solved by that plugin-based approach that you had mentioned, where there's a `screenpy-core` and a `screenpy-selenium`. Then at least all the questions that act on elements would be in `screenpy-selenium`.

Small tangent there. I don't know if tying all these questions into a single one will be maintainable, though. That handcuffs us to updating the `Element` question every time there's a new hook we want to latch onto for `WebElement`. It's `Value` this time, it might be `Attribute` next, who knows.

**Comment by perrygoy** [comment]
... hey, why not just make an `Attribute` Question, eh? `value` is an attribute after all. 🤦
