### ISSUE TITLE
Add way to tell actors they have some cleanup to do.

### ISSUE THREAD

**Issue by pgoy-dod** [perrygoy/screenpy#41]
Currently, when an actor exits, all they do is forget all their abilities. 

It would be neat if we could tell the actors that they have some cleanup tasks to attend to after they are done with their role, but before they forget their abilities.

*Note*: Not totally sure this doesn't violate Single Responsibility Principle, but *i* can rationalize a definition of "responsibility" that includes this, so...

**Comment by bandophahita** [comment]
I like this idea. Maybe it could be a hook into `forget`? 

One of first things I did was to setup my actors so they didn't close down the selenium driver in-between tests.  I recall wishing I could dictate to the actor what `forget` did when it was called. 

```
@pytest.fixture(scope="function")
def imp_specialist(selenium: "WebDriver", user_credentials: Credentials):
    """A simple Actor fixture for the pytest example"""
    actor = Actor.named("Rebecca").who_can(
        BrowseTheWeb.using(selenium),
        Authenticate.with_credentials(user_credentials),
        ManageBrowserLocalStorage.using(selenium),
        )
    yield actor
    # don't close the selenium driver just because the actor exits the stage.
    aside(f"{actor} exits stage left!")
    actor.was_able_to(
        RemoveAbilityWithouClosingSelenium(BrowseTheWeb),
        RemoveAbilityWithouClosingSelenium(ManageBrowserLocalStorage)
        )
    actor.exit_stage_left()
    pass
```

**Comment by pgoy-dod** [comment]
That makes me feel even better about it that you could find it useful. I made a trial run in our suite called `ConscientiousActor` who has a `clean_up` method that runs all the cleanup tasks, and it allows our Pytest fixture to directly call that method before taking one final tear-down screenshot. 

I think i'll put up a PR for it soon!

**Comment by bandophahita** [comment]
Playing devils advocate for a moment: is it up to the actor to cleanup after themselves or is that something the test setup/teardown should do?   I imagine `actor.clean_up()` would get called a lot in teardown.  If teardown is the ONLY place it gets called, the logic added to cleanup would be essentially the same as what happens in teardown; in which case was anything gained?

I have been considering an actor's responsibility; which is to provide the abilities to conduct a test.  In some ways setup of the environment isn't something for which I typically consider the actor would be responsible (i.e. insert data into database, etc). That said something like 'logging out' makes perfect sense to me as being something for which they _are_ responsible.

It's that last part I think of when it comes to having the ability to set what cleanup does for an actor.

**Comment by pgoy-dod** [comment]
Yeah, i had considered making this an ability, like `the_actor.has_ability_to(TearDown())`, but the difficulty there is that tearing down might involve multiple abilities, and they might need to all still be "active" (that is, not forgotten) to accomplish teardown. I can't guarantee that the `TearDown` ability would be forgotten first, so... :(

In our suite's case, we're currently dealing with the un-ideal situation of a persistent database, so we need to do things to "close down" the data we generated so they don't show up in future tests. I had originally been creating separate fixtures that were the same as the other actors, but had cleanup tasks to do. That quickly became unwieldy, whence this issue was created.

The rationalized definition of "responsibility" i have for Actor is that they are custodians of the abilities. That word "custodian" is carefully chosen, because not only do they tend to their creation and use, they also clean up after them! Bullseye.

**Comment by bandophahita** [comment]
> That word "custodian" is carefully chosen, because not only do they tend to their creation and use, they also clean up after them! 

I think what I am hearing is; if cleanup needs to be done it should be done prior to the actor exiting the stage.  It doesn't matter if it's the same actor or two different actors; whatever actions need to occur they will be done before that actor exits.   I think this is sound reasoning since the actors have the abilities to perform whatever actions needed.

What I'm wondering is does establishing the steps the actor should take prior to exit need to be callable BY the actor?

Here is what I'm picturing:
We have an fixture that sets up the actor and in this teardown we tell the actor to delete some rows in a couple tables before exiting the stage.
```
@pytest.fixture(scope="function")
def primary_actor(selenium: "WebDriver", pgconn: "psycopg2.connect"):
    """A simple Actor fixture for the pytest example"""
    actor = Actor.named("billy").who_can(BrowseTheWeb.using(selenium),
                                         ManageDatabase.using(pgconn))
    yield actor
    aside(f"{actor} cleans up after themselves")
    # Tell the actor to do some cleanup.
    actor.was_able_to(DeleteTestData(TABLE_A),
                      DeleteTestData(TABLE_B))
    #####
    actor.exit_stage_left()
```
If we have the option to tell the actor what those steps are to be called later, we still have to tell the actor what those steps are.  

```python
@pytest.fixture(scope="function")
def primary_actor(selenium: "WebDriver", pgconn: "psycopg2.connect"):
    """A simple Actor fixture for the pytest example"""
    actor = Actor.named("billy").who_can(BrowseTheWeb.using(selenium),
                                         ManageDatabase.using(pgconn))
    # tell the actor what the cleanup steps should be.
    actor.whose_teardown_steps_are(DeleteTestData(TABLE_A),
                                   DeleteTestData(TABLE_B))
    yield actor
    aside(f"{actor} cleans up after themselves")
    # exiting will execute the steps established above
    actor.exit_stage_left()
```

Is there any benefit to telling the actor what steps to take, only later?

**Comment by pgoy-dod** [comment]
Yeah, so here is how we're doing it in our suite.

```python
def test_psychiatry_call(..., Patty: ConscientiousActor, ...) -> None:
    """A patient is able to connect to a Psychiatrist."""
    Patty.has_cleanup_task(EndCall())
    # ...
```

We tell the actor what their cleanup tasks are at the beginning of the test. That way the tests keep track of what data is going to be created and can dictate to the actors what the cleanup steps need to be. 

Then, we're using `pytest` fixtures to create our actors, which allows us to do this (they're more complicated than the below, so i'm paraphrasing a little bit):

```python
@pytest.fixture
def Patty():
    the_actor = ConscientiousActor.named("Patty").who_can(BrowseTheWeb.using_chrome())
    yield the_actor
    attach_screenshot("test_finished.png")
    try:
        the_actor.cleans_up()
    finally:
        attach_screenshot("teardown_finished.png")
    the_actor.exit_through_the_vomitorium()
```

Putting the cleanup steps here makes it so we have teardown happen no matter what happened during the test, and also allows for us to attach screenshot information just in case teardown failed for some reason. Even in the Allure reports, all this goes in the "Tear Down" section!

That's the benefit we're using it for. As i mentioned, previously we had the approach to create specialized fixtures like `Patty_endcall` which did the `EndCall()` task after the `yield`, but... we started having a lot more tests that needed to do a lot of different teardowns, and creating specialized actors for each of them was clearly not sustainable, maintainable, or fun to work with.

**Comment by pgoy-dod** [comment]
Oh, i forgot to mention that we can also shortcut if the actor doesn't have any teardown steps:

```python
if len(the_actor.cleanup_tasks) > 1:
    # ...
```

**Comment by bandophahita** [comment]
> We tell the actor what their cleanup tasks are at the beginning of the test.

Ahh, so each test might have different cleanup tasks for the same actor.  Ok, I see the benefit now.

**Comment by pgoy-dod** [comment]
@bandophahita check out the PR i just submitted if you'd like, PR #43!

Typing up this comment right now, i think i should probably add some documentation mentioning the cleanup tasks. I'll get to that tonight.

**Comment by perrygoy** [comment]
PR #43 is merged!
