### ISSUE TITLE
`screenpy-quickstart` should generate a more useful test.

### ISSUE THREAD

**Issue by perrygoy** [perrygoy/screenpy#48]
The `screenpy-quickstart` script generates an example test named "test_example" that doesn't do very much. It should generate a more interesting (and better named) test that at least `Click`s around a little bit. 

Maybe a test that clicks through the Guided Tour on the docs page?

**Comment by bandophahita** [comment]
I wish I had written down notes when I was first trying out the library.  There were a couple times I wish I had examples of something that I was attempting to do.  I seem to recall wishing I had clean examples of not just how to use the library but also how screenplay pattern works.  I'll see what I can conjure up to add to this.

It would great if we could incorporate examples of every action/question to show how they are intended to be used.  I also think it would be extremely useful to show examples of some 'best practice' incorporating screenpy into test suites.  For example; generating fixtures in pytest, taking screenshots in selenium upon failure, etc.

**Comment by perrygoy** [comment]
Yes, that's exactly the kind of thing i'm thinkin' of.

I do have some [example projects](https://github.com/perrygoy/screenpy/tree/trunk/examples) that i put up initially just to show what a "full" project might look like, but they've also been very practical to just... run them, sometimes, to see if ScreenPy still works after i've made some changes. 

I'm not sure how long it's been since you visited the docs, but one of those major overhauls in the last few versions included standardizing all of the docstrings to include examples of the "right" way to use the included [Actions](https://screenpy-docs.readthedocs.io/en/latest/topics/actions.html#provided-actions), [Questions](https://screenpy-docs.readthedocs.io/en/latest/topics/questions.html#provided-questions), and all. Not sure if that's what you meant, though.

Taking screenshots and generating fixtures sound like they would be great additions to the [Recipes](https://screenpy-docs.readthedocs.io/en/latest/cookbook.html) section! :D

**Comment by perrygoy** [comment]
Added one new test to the suite that just clicks through the guided tour. It's got a lot of Actions, that's for sure!

@bandophahita if you think of some of the things you wish you'd written down, please open a new issue or discussion topic for them. I'd love to know what they were!
