### ISSUE TITLE
README should mention that path to `screenpy-quickstart.py` needs to be specified

### ISSUE THREAD

**Issue by langgaibo** [perrygoy/screenpy#49]
When following the README, I did the following:
`$ pip3 install screenpy`
`$ screenpy-quickstart`

According to the documentation, installing screenpy via pip should add the quickstart script in a manner that allows it to be run as above, but this doesn't appear to be the case.

I'm using virtualenv, and i see the `screenpy-quickstart.py` script is in `env/bin/`.

I'm only able to run the script as follows:
`$ python3 path/to/the/screenpy-quickstart.py`

Maybe this is only an issue that presents for fools such as myself. But I'm a fool that loves to complain!

**Comment by perrygoy** [comment]
@langgaibo i made a mention of it. I did also notice when installing a fresh `screenpy` that i got some warnings about the Python scripts directory not being on my path (i can't get it to happen again now, for some reason).

I thought it would be cool to add that warning to ScreenPy, too, but i can't find anything online about how to do that! All the results were just people asking about the warnings they get. Haha. Hopefully the new README line is good enough?

**Comment by perrygoy** [comment]
For reference this is the line i added:

> Note that the Python script directory will need to be on your path to find `screenpy-quickstart`.
