### ISSUE TITLE
Incorrect type hint for Target.locator

### ISSUE THREAD

**Issue by bandophahita** [perrygoy/screenpy#58]
The typehint for `Target.locator` is `locator: Union[None, Tuple[By, str]]`.  I believe this is incorrect.

The locator tuple is supposed to be two strings.  The `By` object as a typehint isn't equivalent to a string.

**Comment by perrygoy** [comment]
That does indeed seem to be the case, as `By` is just a holder for a bunch of strings: https://github.com/SeleniumHQ/selenium/blob/trunk/py/selenium/webdriver/common/by.py

**Comment by perrygoy** [comment]
Fixed! It'll go out with the next release.
