### ISSUE TITLE
Add a way to toggle on/off logging.

### ISSUE THREAD

**Issue by perrygoy** [perrygoy/screenpy#62]
It turns out, sometimes you *don't* want to log! 

In Discussion #20, @bandophahita is attempting to create a new `Eventually` action that can take an assertion and just keep trying it until a given timeout. All those tries... are logged. 😬 

We could use a way to toggle off logging, maybe as a context manager (i.e. `with no_logs():`, maybe a cool screenplay-themed one like `no_voiceover()` or something as sugar).

**Comment by bandophahita** [comment]
It is unclear to me how serenity does this; but one aspect of being able to turn off logging is knowing exactly what to log and when.  

So in the example of `Eventually` seeing an element is clickable; Do we want to log the fact that we are looking and then log the fact that it did or didn't happen afterward?  

```
13:30:19  INFO [QUESTION] Admin looks for Logout Button to be present (eventually)

#### a whole lot of looping is going on here but not logged.  
#### Once it is found/times out then log the final resolution?

13:30:29  INFO ... hoping it's clickable
13:30:29  INFO     => False
```

**Comment by perrygoy** [comment]
Hm, that's a good question. I think we want to know what the actor is waiting to eventually be true, and how long it took to be true. Something like this from the logs:

```
13:30:19  INFO [QUESTION] Admin looks for Logout Button to be present (eventually)
13:30:29  INFO     ... and it was, after 10 seconds!
```

Might as well use that timeout checking for loggin' eh? 

I'm not sure yet how easy it will be to essentially re-craft the logged beats in `Eventually`. I've been thinking i might need to rethink how `beat`s work. 😟

**Comment by bandophahita** [comment]
> we want to know what the actor is waiting to eventually be true, and how long it took to be true.

Opinion: Logging the wait timeout duration should occur before the actual waiting.  This would give an indication to the reader that we're about to wait X duration. The real-time feedback of what is _about to happen_ is already very prevalent in the library.

Doing so would avoid having to keep track of how long the actual waiting was.  Plus timestamps in the log between the question and the answer would also serve as an indication of actual duration vs timeout limit.


```
13:30:20 INFO [QUESTION] Admin looks for Logout Button to be present for up to 10 seconds...
13:30:27 INFO    => <selenium.webdriver.remote.webelement.WebElement (session="f1f76015cd61e9627dd28c7453e3c509", element="0.554498065929625-1")>
13:30:27 INFO ... hoping it's clickable
13:30:27 INFO      => True
```

That said, I'm not completely against logging the actual duration.  While I might have some soap box feelings about not combining performance testing with user testing, there could be some real-world cases where logging the duration could be useful.

**Comment by bandophahita** [comment]
Using the beat decorator as it current is, I came up with a quick-and-dirty solution that could work provided we figure out how to silence the logging properly while looping.
```
14:14:30  INFO Admin waits no longer than 5 seconds for...
14:14:30  INFO     [QUESTION] Admin looks for Username Field to be present
14:14:30  INFO         => <selenium.webdriver.remote.webelement.WebElement (session="3e1a84af19e93c5cb212b2bef2adb60f", element="0.7623352388995115-1")>
14:14:30  INFO     ... hoping it's clickable
14:14:30  INFO         => True
```

The above logging happens using `Eventually` like this:
```python
administrator.should(
        Eventually(
            See(PresentElement(USERNAME_FIELD), IsClickable())
            ).waiting_no_longer_than(5).seconds()
        )
```
The perform_as method in `Eventually` simply has the beat decorator:
```python
    @beat("{} waits no longer than {timeout} seconds for...")
    def perform_as(self, actor: "Actor") -> None:
        ...
```

I could live with this.  
Granted it _would be_ cooler if my previous comment were to be possible.

**Comment by perrygoy** [comment]
I could also live with that!

I have gone back and forth on adding `__repr__`/`__str__` methods to the Questions that would just describe what the Question is going to ask. This might be an actual, practical use for that. Resolutions already have the `get_line` method that we could use to furnish that part of the sentence.

**Comment by perrygoy** [comment]
@bandophahita i created #64 so we can discuss it. 

You were right in our chat about `global`. I hadn't fully thought it out, haha. I ended up making a `settings` file with only one setting, but it makes me wonder if there would be more things that would be nice to be in there. It's also currently, you know, just a module with constants in it. 

I was looking at how [Django's settings](https://github.com/django/django/blob/main/django/conf/__init__.py) are implemented, but i don't think we need to go all that deep just yet.

**Comment by perrygoy** [comment]
Phew! It's been a long time coming, but this has finally been addressed. Folks can now do this:

```python
from screenpy.pacing import the_narrator

with the_narrator.mic_cable_kinked():
    # while in this context, no logging occurs
    the_actor.attempts_to(
        DoSomeThings(),
    )
# when leaving the context, all logging is flushed out

with the_narrator.off_the_air():
    # while in this context, all logging is turned off - not even backed up
    the_actor.attempts_to(
        DoSomeThings(),
    )
# leaving does not flush the log
```
