### ISSUE TITLE
Allow `MakeNote` to accept a question or a value.

### ISSUE THREAD

**Issue by pgoy-dod** [perrygoy/screenpy#66]
OK, this is the *n*th time i've tried to do `MakeNote.of_the("some value").as_("name")`. It seems totally intuitive. 

Let's make it happen.

**Comment by perrygoy** [comment]
Probably also `See` could do with this benefit as well!

**Comment by perrygoy** [comment]
`See` and `MakeNote` now both allow values to be used directly!

```python
test = "test"

the_actor.attempts_to(MakeNote.of(test).as_("test note"))

the_actor.should(See(the_noted("test note"), IsEqualTo(test))
```
