### ISSUE TITLE
Improve `IsVisible` Assertion Failure Message

### ISSUE THREAD

**Issue by pgoy-dod** [perrygoy/screenpy#69]
If an assertion that an element is not visible fails, this is what it looks like:

```python traceback
    def perform_as(self, the_actor: Actor) -> None:
        """Direct the Actor to make an observation."""
>       assert_that(self.question.answered_by(the_actor), self.resolution)
E       AssertionError:
E       Expected: not the element is visible.
E            but: but was <selenium.webdriver.remote.webelement.WebElement (session="835c37e586c0c2d00bee8f0069c92cb7", element="90a21c2c-3c3c-4001-a1b1-5aff97924e4c")>
```

That is not very easy to look at. Try to make it nicer!

**Comment by perrygoy** [comment]
Looking through the PyHamcrest source and how the `is_not` matcher plays with our custom `is_visible` matcher, this might just be How It Works unfortunately. :\

**Comment by perrygoy** [comment]
Just kidding! Turns out i just needed to add a [`describe_match` method](https://pyhamcrest.readthedocs.io/en/v2.0.2/core/#hamcrest.core.base_matcher.BaseMatcher.describe_match).

**Comment by perrygoy** [comment]
Fixed!
