### ISSUE TITLE
Add `SaveScreenshot` and `SaveConsoleLog` Actions.

### ISSUE THREAD

**Issue by pgoy-dod** [perrygoy/screenpy#81]
Hey it sure would be nice to have these as actions, i'm sure other people would have need of them. Here's how i imagine it would look to use it:

```python
the_actor.attempts_to(
    SaveScreenshot.as_(filepath).and_attach_it(attachment_type=AttachmentType.PNG),
    SaveConsoleLog.as_(js_path).and_attach_it(attachment_type=AttachmentType.TEXT),
)
```

The `and_attach_it` method would take any additional keywords that the adapters might expect, or none if the suite doesn't use any adapters that expect kwargs. The example above uses the `AllureAdapter`, so it passes Allure's attachment type.

**Comment by perrygoy** [comment]
Closed by #82!
