### ISSUE TITLE
`AttributeError` is too broad for `MakeNote` and `See`.

### ISSUE THREAD

**Issue by pgoy-dod** [perrygoy/screenpy#83]
Catching `AttributeError` works for seeing if the passed-in value has an `.answered_by` method, but it is a little too broad. It can be a false-positive if a Question uses some functions that cause an `AttributeError`, leading to the Question itself being treated as a value. This is not easy to debug. ":D

Change these two to use `hasattr` instead!

**Comment by perrygoy** [comment]
Closed with [f9902e1](https://github.com/perrygoy/screenpy/commit/f9902e10989f6166ca8772f24454200ab3f037f3)!
