### ISSUE TITLE
Adding selenium feature `staleness_of`?

### ISSUE THREAD

**Issue by MarcelWilson** [perrygoy/screenpy#89]
Consider the following context manager which ensures the page changes as a means of script synchronization.
```python
    @contextmanager
    def wait_for_content_page_load():
        logger.debug("fetching original page to compare staleness later.")
        old_page = driver.find_element_by_tag_name("html")
        yield
        logger.debug(f"{verb.WAITING} Content page to load")
        wait.until(staleness_of(old_page), "page never became stale!!!")
```
used like so:
```python
with wait_for_content_page_load():
    driver.find_element().click()
```
This functionality works rather well outside a screenplay pattern.  I'm trying to envision how to implement this in screenpy and would love some feedback.

I was sorta thinking the usage might look something like this:
```python
actor.was_able_to(WaitForPageChangeAfter(Click.on(BUTTON))
```

**Comment by perrygoy** [comment]
My team actually ran into this same quandary. It is technically possible to do this in ScreenPy currently, like so:

```python
the_element = TARGET.found_by(the_actor)
the_actor.attempts_to(
    Click.on_the(BUTTON),
    Wait.using(staleness_of, f"Until {TARGET} is stale...").with_(the_element),
)
```

It is a little clumsy, but i don't know if there's a way to just say `Wait.for_the(TARGET).to_become_stale()`, especially if there need to be Actions in between.

**Comment by MarcelWilson** [comment]
The trick of this is `the_element` must be fetched prior to `Click.on_the(BUTTON)` and then utilized in a `staleness_of` check.  It's partially why the context manager version is so great.  I had originally figured I'd be able to replicate the context manager in screenplay, but either it doesn't lend itself to that pattern or I just can't figure out how to make it work.

I effectively recreated your above example but then just wrapped it within its own action class.  

```python
class WaitForPageChangeAfter(Performable):
    @beat("[TASK] {} attempts to {performable_to_log} then WaitForPageChangeAfter ")
    def perform_as(self, actor: Actor):
        #TODO: likely need resolution IsStale()
        old_element = HTML_ROOT.found_by(actor)
        actor.was_able_to(self.performable)
        actor.should(Eventually(See(StalenessOfElement(old_element), IsEqualTo(True))))
        return

    def describe(self) -> str:
        """describe the action in present tense"""
        return f"Wait for Page to Change after {self.performable_to_log}"

    def __init__(self, performable: Performable):
        self.performable = performable
        self.performable_to_log = get_additive_description(self.performable)
        self.old_element = None


class StalenessOfElement:
    def answered_by(self, actor: Actor):
        return staleness_of(self.element)(None)

    def __init__(self, element: "WebElement"):
        self.element = element
```

**Comment by perrygoy** [comment]
You're right, of course—you can't find the element until the actor is there! You can do it with a custom condition, though, like this:

```python
def staleness_of_target(target: Target) -> Callable:
    def _predicate(driver: Remote) -> bool:
        return EC.staleness_of(driver.find_element(*target))

    return _predicate
    
# Then in your actions:

the_actor.attempts_to(Wait().using(staleness_of_target).with_(TARGET))
```

I think a recipe might be a good idea for this case, yes.
