### ISSUE TITLE
Synchronization handling

### ISSUE THREAD

**Issue by MarcelWilson** [perrygoy/screenpy#91]
### Prologue: 
Anyone with some experience using selenium quickly learns (in my case, the hard way) that synchronization is vital to the longevity of a test suite.  In most cases tests will run just fine until that one time where the site is a bit slower (or even a bit faster) and suddenly tests are failing.  

"What do you mean can't find the element, I'm staring right at it!?" 

That's where we start employing various synchronization techniques; explicit waits for expected elements, page reloads, url changes, etc.   There are a bunch of them.

### Discussion:
In my experience the synchronization techniques which work best are often situationally dependent on the site architecture.  

#### Examples: 
If a site url changes with every button click we can use that to know that the old page is no longer present (note - timing wise it could be dangerous to assume the new page has finished loading)  Using that technique on a site whose url never changes would of course not work at all.  

If a site uses ajax, quite often a need arises to wait until jquery has finished before dynamic elements have populated. Obviously this wouldn't apply to sites that do not use ajax at all, but even amongst sites that do use ajax, the technique doesn't always work; i.e. cases where jQuery is sporadically starting and stopping.  

- waiting for `document.readyState == 'complete'`
- waiting for element to become stale
- waiting for js function to be defined 

In my first test suite using screenplay pattern I found myself creating actions which used these techniques.  That got me thinking that perhaps we should include more of these actions into the package.  What I'm most concerned with is adding code that might be better off in the recipes examples.  The question is how specific is _too_ specific?  How generic is generic enough to warrant inclusion in the package?

**Comment by perrygoy** [comment]
I feel like the synchronizations you're talking about are going to be highly dependent on what kind of website is being automated. Single Page Apps will be different from traditional websites, some websites will have different "tells..." in other words, i don't think we'll be able to include things that i feel are generic enough to belong in base ScreenPy.

Recipes, though, i do think would be useful! The good news is that the examples you gave are all possible with the current base using `Wait`, but having Recipes to show how is a good idea.

**Comment by perrygoy** [comment]
My final thoughts on this are that if we find some Actions that you can take from your project and apply them to a brand new project without any configuration, that's an Action that might be a candidate for inclusion in ScreenPy itself. 

For now, it seems like `Wait` covers all the scenarios described above, so i'm going to close this issue. (I'm cleaning stuff out for the 4.0 release in a few weeks!)
