### ISSUE TITLE
Add `aside` when `See` compares a value instead of a Question

### ISSUE THREAD

**Issue by pgoy-dod** [perrygoy/screenpy#92]
When `See` compares an existing value against a `Resolution`, there's no log to say what the actual value is. Something simple like "{the_actor} considers {value}..."

**Comment by pgoy-dod** [comment]
I thought of some more minor updates that will help readability/insight.

Sometimes you might intentionally have a locator that can find multiple elements. For example, you might have a `TODO_ITEMS` locator that finds all the todo items on your todo list. When you do `Text.of_all(TODO_ITEMS)`, you will get an array back of all the texts of the todo items. 

But when you do `Text.of_the(TODO_ITEMS)`, it will only get the text of the first item. You probably know this, also, while you write the test, and that's what you want it to do. However, _reading_ that line makes you think it will behave the same as `Text.of_all(TODO_ITEMS)`, right?

I think adding an alias method named `of_the_first_of_the` would allow folks to make it much clearer. I think a few actions and questions can benefit from these kinds of methods:

* `Click`
* `Clear`
* `DoubleClick`
* `Enter`
* `MoveMouse`
* `RightClick`
* `Attribute`
* `Text`

**Comment by pgoy-dod** [comment]
... and now i realize that this is a completely separate ticket. Moving it!

**Comment by perrygoy** [comment]
Fixed!
